github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: brew install warrensbox/tap/tfswitch && pip install awscli
    init: brew install warrensbox/tap/tfswitch && pip install awscli # runs during prebuild
    command: tfswitch 1.0.2 && export PATH=/home/gitpod/bin:$PATH && export AWS_PROFILE=academy


vscode:
  extensions:
    -  hashicorp.terraform

